#!/usr/bin/env python3
"""
rxmedcalc.com — FAQ Injector v2
Injects static HTML FAQ sections before </body> for pages with no FAQ.
Run from repo root: python3 inject_faqs_v2.py
"""
import re, shutil
from pathlib import Path

# FAQ CSS to inject if .fi/.fq not present
FAQ_CSS = """
    .faq-sec{margin:28px 0}.faq-sec h2{font-size:1.05rem;font-weight:700;color:var(--primary-dark,#0c4a6e);margin-bottom:14px;padding-bottom:8px;border-bottom:2px solid var(--border,#dce4ef)}
    .fi{border-bottom:1px solid var(--border,#e5e7eb);padding:14px 0}.fi:last-child{border-bottom:none}
    .fq{font-size:0.9rem;font-weight:600;color:var(--text,#0d1b2a);cursor:pointer;display:flex;justify-content:space-between;align-items:flex-start;gap:10px;user-select:none}
    .fq::after{content:'＋';color:var(--primary,#0369a1);font-size:1rem;flex-shrink:0;transition:transform 0.2s}
    .fi.op .fq::after{transform:rotate(45deg)}
    .fa{max-height:0;overflow:hidden;transition:max-height 0.35s ease;font-size:0.85rem;color:var(--text-muted,#4b5563);line-height:1.75}
    .fi.op .fa{max-height:600px;padding-top:8px}"""

FAQ_JS = """
  function tf(el){var fi=el.closest('.fi');var was=fi.classList.contains('op');document.querySelectorAll('.fi').forEach(function(e){e.classList.remove('op')});if(!was)fi.classList.add('op')}"""

def build_faq_html(faqs):
    items = []
    for q, a in faqs:
        items.append(
            f'      <div class="fi"><div class="fq" onclick="tf(this)">{q}'
            f'</div><div class="fa">{a}</div></div>'
        )
    return (
        '\n  <div class="faq-sec">\n'
        '    <h2>Frequently Asked Questions</h2>\n'
        + '\n'.join(items) +
        '\n  </div>'
    )

# ── FAQ DATA ─────────────────────────────────────────────────────────
FAQS = {
"aa-gradient": [
    ("What is the A-a gradient?", "The alveolar-arterial (A-a) gradient is the difference between the partial pressure of oxygen in the alveoli (PAO2, calculated) and in arterial blood (PaO2, measured on ABG). A normal gradient means efficient oxygen transfer. An elevated gradient indicates a gas exchange problem — V/Q mismatch, diffusion defect, or right-to-left shunt."),
    ("What is the normal A-a gradient?", "The normal A-a gradient is age-dependent: approximately Age/4 + 4 mmHg on room air. For a 40-year-old, normal is ~14 mmHg. On 100% O2, the normal upper limit rises to ~100 mmHg. Values significantly above these thresholds suggest impaired gas exchange."),
    ("What causes an elevated A-a gradient?", "Common causes: V/Q mismatch (PE, pneumonia, COPD, asthma, pulmonary oedema), diffusion defect (interstitial lung disease, ARDS), right-to-left shunt (intracardiac defect, hepatopulmonary syndrome). A normal A-a gradient with hypoxia suggests hypoventilation — check PaCO2."),
    ("When should A-a gradient be used over P/F ratio?", "A-a gradient is most reliable on room air (FiO2 0.21). At higher FiO2 levels the gradient naturally widens, reducing discriminatory value. In patients on supplemental oxygen, the P/F ratio (PaO2/FiO2) is preferred — it is independent of FiO2 and is the standard oxygenation index in ICU (normal >400, ARDS <300)."),
    ("What is the PAO2 formula?", "PAO2 = (FiO2 × [Patm − PH2O]) − (PaCO2 / RQ). At sea level on room air: PAO2 = (0.21 × 713) − (PaCO2 / 0.8). PH2O at 37°C = 47 mmHg, Patm = 760 mmHg, RQ = 0.8 assumed. The A-a gradient = PAO2 − PaO2 (from ABG)."),
    ("Is A-a gradient useful for diagnosing PE?", "A raised A-a gradient raises suspicion for PE but is non-specific — nearly 20% of proven PEs have a normal gradient. It should not be used in isolation. Use Wells score + D-dimer → CTPA pathway for PE diagnosis. A-a gradient is more useful to confirm that hypoxia has a pulmonary cause rather than hypoventilation alone."),
],
"albumin-corrected-ag": [
    ("Why is albumin correction needed for the anion gap?", "Albumin is a major unmeasured anion. Hypoalbuminaemia (common in liver disease, nephrotic syndrome, malnutrition, critical illness) falsely lowers the anion gap. Without correction, a significant high-AG acidosis may be missed. Corrected AG = Measured AG + 2.5 × (4.0 − Albumin g/dL)."),
    ("What is the normal anion gap?", "Normal anion gap = 8–12 mEq/L (using Na − Cl − HCO3). When albumin-corrected, the reference range is the same. Each 1 g/dL fall in albumin below 4.0 g/dL lowers the AG by ~2.5 mEq/L — so a patient with albumin 2.0 g/dL and AG of 10 actually has a corrected AG of 15, indicating a high-AG acidosis."),
    ("What are the causes of high anion gap metabolic acidosis?", "Mnemonic MUDPILES: Methanol, Uraemia, Diabetic ketoacidosis, Propylene glycol/Paracetamol toxicity, Isoniazid/Iron, Lactic acidosis (sepsis, shock, metformin), Ethylene glycol, Salicylates. In Indian emergency practice, most common are DKA, lactic acidosis (sepsis), and uraemia."),
    ("What is the delta ratio?", "Delta ratio = (AG − 12) / (24 − HCO3). Detects mixed disorders: <0.4 = normal AG acidosis co-exists, 0.4–0.8 = combined high AG + normal AG acidosis, 1–2 = pure high AG acidosis, >2 = concurrent metabolic alkalosis. Always calculate when AG is elevated."),
    ("What is normal anion gap acidosis?", "NAGMA (hyperchloraemic acidosis) causes: diarrhoea (most common in India — HCO3 loss), renal tubular acidosis, early CKD, ureteral diversion, excessive normal saline infusion. Urine anion gap (Na + K − Cl) differentiates renal (positive UAG) from GI (negative UAG) causes."),
    ("How does albumin affect the delta ratio calculation?", "In hypoalbuminaemic patients, both the measured AG and the corrected AG differ. Use the albumin-corrected AG in the delta ratio numerator: Delta ratio = (Corrected AG − 12) / (24 − HCO3). Using the uncorrected AG in hypoalbuminaemic patients underestimates the severity of the high-AG acidosis."),
],
"apache2-score": [
    ("What is APACHE II used for?", "APACHE II (Acute Physiology and Chronic Health Evaluation II) estimates ICU mortality risk using 12 acute physiological variables, age, and chronic health status. Scores range 0–71. It is used for ICU benchmarking, clinical research stratification, prognosis estimation, and family discussions — not for individual treatment-limitation decisions."),
    ("What APACHE II score predicts high mortality?", "Score 0–9: <10% mortality. Score 10–19: 15–25%. Score 20–24: ~40%. Score 25–29: ~55%. Score 30–34: ~73%. ≥35: >85%. These are population estimates. Actual mortality depends on diagnosis, ICU interventions, and centre-level factors."),
    ("What are the 12 physiological variables in APACHE II?", "Temperature (rectal), mean arterial pressure, heart rate, respiratory rate, oxygenation (A-a gradient or PaO2), arterial pH, serum sodium, serum potassium, creatinine, haematocrit, white cell count, and GCS. Each scored 0–4 based on deviation from normal using worst values in first 24 ICU hours."),
    ("What chronic conditions add APACHE II points?", "5 points added for non-operative or emergency surgical patients with: liver cirrhosis with portal hypertension, NYHA Class IV heart failure, severe COPD/chronic hypoxia, chronic renal replacement therapy, or immunosuppression (chemotherapy, steroids, AIDS). 2 points for elective surgical patients with same conditions."),
    ("How does APACHE II compare to SOFA?", "APACHE II is calculated once at ICU admission — it is a severity-at-admission score. SOFA is calculated daily to track organ failure trajectory. A rising SOFA predicts poor outcome better than a high initial APACHE II. Use APACHE II for admission severity; SOFA for daily monitoring and sepsis definition."),
    ("Is APACHE II validated in Indian ICUs?", "APACHE II has been validated in multiple Indian ICU studies and performs reasonably well, though it tends to overestimate mortality in Indian populations compared to the original Western derivation cohort. Several Indian studies suggest calibrating with local mortality data. Despite this, it remains the most widely used ICU severity score in India."),
],
"apgar-score": [
    ("What does each Apgar component assess?", "Appearance (skin colour): 0=blue/pale all over, 1=blue extremities body pink, 2=completely pink. Pulse: 0=absent, 1=<100, 2=≥100 bpm. Grimace (reflex): 0=none, 1=grimace, 2=cry/cough/sneeze. Activity (tone): 0=limp, 1=some flexion, 2=active motion. Respiration: 0=absent, 1=weak/irregular, 2=strong cry."),
    ("What Apgar score requires immediate resuscitation?", "Score 7–10: normal, routine care. Score 4–6: moderate depression — stimulation, supplemental O2, consider PPV. Score 0–3: severely depressed — immediate resuscitation: warmth, airway, PPV, if HR <60 despite PPV then chest compressions (3:1 ratio), then IV/IO adrenaline 0.01 mg/kg if HR still <60."),
    ("When exactly is Apgar score assessed?", "At 1 minute and 5 minutes after birth. The 1-minute score guides immediate resuscitation. The 5-minute score reflects response to resuscitation and predicts outcome better. If 5-minute score <7, repeat at 10, 15, and 20 minutes until ≥7 on two consecutive assessments."),
    ("Does low Apgar predict long-term outcome?", "A low 1-minute score alone does not reliably predict long-term outcome — many resuscitate well and develop normally. A persistently low 5-minute score (<3) is associated with higher risk of cerebral palsy and neurodevelopmental delay but is not diagnostic. Apgar is a resuscitation guide, not a neurological prognosis tool."),
    ("What is the Apgar score in preterm infants?", "Standard Apgar is less reliable in preterm infants where low tone, colour, and respiratory effort are expected physiologically. The Expanded Apgar score includes gestational age context. NRP now emphasises HR, respiratory effort, and tone as primary resuscitation triggers rather than Apgar total score alone."),
    ("What causes a low Apgar score?", "Intrapartum asphyxia (most common), prematurity, maternal sedation (opioids, magnesium toxicity), congenital anomalies (diaphragmatic hernia, CHD), infection (chorioamnionitis, early-onset sepsis), and neuromuscular conditions. In India, prolonged obstructed labour and home deliveries without skilled attendance are important preventable causes."),
],
"bisap-score": [
    ("What does BISAP stand for?", "BISAP: BUN >25 mg/dL, Impaired mental status (GCS <15), SIRS criteria present (≥2 of: temp <36 or >38°C, HR >90, RR >20 or PaCO2 <32, WBC <4000 or >12000), Age >60 years, Pleural effusion on imaging. Each criterion = 1 point, total 0–5, calculated in first 24 hours."),
    ("What BISAP score indicates severe pancreatitis?", "Score 0: <1% mortality. Score 1: ~1-2%. Score 2: ~3-5%. Score 3: ~5-10%. Score 4: ~15-20%. Score 5: >20%. BISAP ≥3 indicates severe acute pancreatitis requiring ICU-level monitoring, aggressive IV fluid resuscitation, and specialist input."),
    ("How is acute pancreatitis managed?", "Early aggressive IV fluid resuscitation (Lactated Ringer's preferred — reduces SIRS vs normal saline), adequate analgesia (IV morphine or tramadol), NPO initially then early enteral nutrition via NGT at 24-48 hours (reduces infected necrosis), monitoring for organ dysfunction. Antibiotics only if infected necrosis confirmed."),
    ("When is CT scan needed in pancreatitis?", "CT abdomen with contrast (CECT) is indicated if: diagnosis is uncertain, or at 72-96 hours if patient is not improving — to assess necrosis extent (Balthazar grade/CT Severity Index). CT is not routinely needed in mild pancreatitis with clear clinical improvement. MRCP is preferred for biliary anatomy assessment."),
    ("What is the difference between BISAP and Ranson criteria?", "Ranson criteria uses 11 parameters — 5 at admission and 6 at 48 hours — requiring a full 2-day wait before complete calculation. BISAP uses 5 parameters all available within 24 hours. Both have similar predictive accuracy (AUC ~0.82). BISAP is preferred for early risk stratification."),
    ("When is ERCP indicated in acute pancreatitis?", "ERCP is indicated only when: cholangitis is present (urgent within 24 hours), or persistent biliary obstruction without cholangitis (within 72 hours). ERCP is NOT indicated in mild gallstone pancreatitis without biliary obstruction. Early cholecystectomy (same admission in mild cases) prevents recurrence and replaces prophylactic ERCP."),
],
"bsa-calculator": [
    ("What is body surface area used for?", "BSA is used to calculate chemotherapy doses (most chemo drugs are dosed per m²), check cardiac index (CI = CO/BSA, normal 2.5–4.0 L/min/m²), calculate renal function (GFR is indexed to 1.73 m² BSA), and dose other drugs with narrow therapeutic windows where weight alone is insufficient."),
    ("Which BSA formula is most accurate?", "No single formula is universally superior. Mosteller (√[height×weight/3600]) is simplest and widely used. DuBois formula (Weight^0.425 × Height^0.725 × 0.007184) is the historical reference standard. Boyd formula is most accurate in children and extremes of weight. For clinical use, Mosteller is recommended for its simplicity with comparable accuracy to DuBois."),
    ("Is BSA-based chemotherapy dosing accurate?", "BSA-based dosing reduces inter-patient variability in drug exposure compared to flat dosing, but does not eliminate it. Actual drug clearance is influenced by organ function (renal, hepatic), body composition, genetics (pharmacogenomics), and drug interactions. Many oncology centres now use therapeutic drug monitoring (TDM) for drugs like carboplatin (AUC-based Calvert formula) rather than BSA alone."),
    ("What is cardiac index and how does BSA relate to it?", "Cardiac index (CI) = Cardiac output (L/min) / BSA (m²). Indexing to BSA accounts for body size differences. Normal CI: 2.5–4.0 L/min/m². CI <2.0 L/min/m² indicates cardiogenic shock. CI is measured by thermodilution (pulmonary artery catheter), echocardiography, or pulse contour analysis. BSA calculation is therefore essential for haemodynamic monitoring in ICU."),
    ("How is BSA different from BMI?", "BMI = weight/height² — measures weight relative to height as a proxy for body fat. BSA = calculated surface area of the body — used for drug dosing and physiological indexing. BSA accounts for both height and weight differently than BMI and does not assess adiposity. A tall, muscular patient may have high BSA but normal BMI; an obese patient may have elevated BMI and BSA."),
    ("What is the normal BSA for Indian adults?", "Average BSA for Indian adults: approximately 1.6–1.7 m² for women and 1.7–1.9 m² for men, somewhat lower than the Western reference of 1.73 m² used for GFR indexing. This difference is clinically significant for chemotherapy dosing — Indian oncology guidelines recommend using calculated BSA rather than a fixed value, with capping at 2.0 m² for obese patients in some protocols."),
],
"creatinine-clearance": [
    ("What is the Cockcroft-Gault formula?", "CrCl (mL/min) = [(140 − Age) × Weight (kg)] / [72 × Serum Creatinine (mg/dL)], multiplied by 0.85 for females. It uses actual body weight for normal-weight patients, ideal body weight for obese patients (ABW >30% above IBW), and adjusted body weight for mildly obese patients. It estimates creatinine clearance, not GFR."),
    ("When is CrCl preferred over eGFR?", "Creatinine clearance by Cockcroft-Gault is preferred for drug dosing — especially in elderly, obese, or underweight patients — because it is not indexed to body surface area and directly estimates drug clearance. eGFR (CKD-EPI) is preferred for CKD staging and diagnosis. Most drug SmPCs (package inserts) specify dose adjustments based on CrCl, not eGFR."),
    ("What drugs need dose reduction with low CrCl?", "Key drugs requiring CrCl-based dose reduction: metformin (stop if CrCl <30, caution 30–45), enoxaparin (reduce dose if CrCl <30, switch to UFH), direct oral anticoagulants (apixaban, rivaroxaban — check individual SmPC), gabapentin/pregabalin, allopurinol, digoxin, aminoglycosides, most beta-lactam antibiotics, and acyclovir."),
    ("How does muscle mass affect creatinine clearance?", "Serum creatinine is a product of muscle metabolism. Patients with low muscle mass (elderly, malnourished, amputees, cirrhosis) have low serum creatinine that overestimates kidney function — Cockcroft-Gault will give a falsely high CrCl. In these patients, cystatin C-based eGFR or 24-hour urine creatinine collection gives more accurate results."),
    ("What is the difference between CrCl and GFR?", "GFR measures pure glomerular filtration. CrCl overestimates GFR by 10–15% because creatinine is also secreted by renal tubules (not just filtered). In normal kidneys this difference is small. In CKD, tubular secretion contributes more proportionally, so CrCl overestimates GFR more significantly. eGFR equations (CKD-EPI) correct for this mathematically."),
    ("How is CrCl calculated in obese patients?", "In obesity (BMI >30), use ideal body weight (IBW) for CrCl calculation, not actual body weight — using ABW in obese patients overestimates CrCl. Exception: some guidelines use adjusted body weight (AdjBW = IBW + 0.4 × [ABW − IBW]) for aminoglycoside dosing in obesity. For enoxaparin in morbid obesity (BMI >40), use actual body weight and monitor with anti-Xa levels."),
],
"fena-calculator": [
    ("What is FENa and what does it measure?", "Fractional Excretion of Sodium (FENa) measures what percentage of filtered sodium is excreted in the urine. Formula: FENa (%) = (Urine Na × Plasma Cr) / (Plasma Na × Urine Cr) × 100. It differentiates prerenal AKI (kidney conserving sodium) from intrinsic renal AKI (kidney unable to conserve sodium)."),
    ("How is FENa interpreted?", "FENa <1%: prerenal AKI — kidneys are functioning normally but underperfused; respond to volume resuscitation. FENa >2%: intrinsic renal AKI (ATN) — tubular damage prevents sodium reabsorption. FENa 1–2%: indeterminate — consider clinical context. In oliguric patients on diuretics, use FEUrea instead (FEUrea <35% = prerenal)."),
    ("When is FENa unreliable?", "FENa is unreliable in: patients on diuretics (artificially raises FENa even in prerenal states — use FEUrea instead), contrast nephropathy (can show low FENa despite ATN), myoglobinuria/haemoglobinuria, acute glomerulonephritis, and early urinary obstruction. Always interpret FENa alongside clinical context, urine microscopy, and response to fluids."),
    ("What is FEUrea and when is it used?", "FEUrea = (Urine Urea × Plasma Cr) / (Plasma Urea × Urine Cr) × 100. FEUrea <35%: prerenal. FEUrea >50%: intrinsic renal (ATN). FEUrea is preferred over FENa in patients on diuretics because diuretics do not significantly affect urea reabsorption. It requires urine and plasma urea levels alongside creatinine."),
    ("What is the treatment of prerenal AKI?", "Prerenal AKI: IV fluid resuscitation (crystalloid — Ringer's Lactate preferred over normal saline for large volumes), identify and treat the underlying cause (bleeding, sepsis, dehydration, cardiac failure, hepatorenal syndrome). Response to fluids (rising urine output, falling creatinine) confirms prerenal aetiology. Avoid nephrotoxins (NSAIDs, aminoglycosides, contrast) during AKI."),
    ("What urine findings suggest ATN vs prerenal AKI?", "Prerenal AKI: urine osmolality >500 mOsm/kg, urine Na <20 mEq/L, FENa <1%, urine specific gravity >1.020, urine microscopy — normal or hyaline casts only. ATN (intrinsic): urine osmolality <350 mOsm/kg, urine Na >40 mEq/L, FENa >2%, urine specific gravity ~1.010, urine microscopy — muddy brown granular casts (pathognomonic of ATN)."),
],
"framingham-risk": [
    ("What does the Framingham Risk Score calculate?", "The Framingham Risk Score estimates the 10-year risk of a first major cardiovascular event (myocardial infarction, coronary death, or angina) based on age, sex, total cholesterol, HDL cholesterol, systolic BP, BP treatment status, diabetes, and smoking. It was derived from the Framingham Heart Study cohort and is one of the oldest validated CVD risk tools."),
    ("How is Framingham risk classified?", "10-year CVD risk: Low: <10%. Intermediate: 10–20%. High: >20%. Patients with established CVD or diabetes are automatically high risk. High-risk patients benefit from statin therapy, BP control to <130/80 mmHg, and antiplatelet therapy (if established CVD). Intermediate-risk patients require individualised decisions."),
    ("Does Framingham risk apply to Indian patients?", "The Framingham equations were derived from predominantly White American populations and overestimate risk in some ethnic groups while underestimating in South Asians. Indians develop CVD at younger ages and at lower risk factor levels. The INTERHEART study showed South Asians have higher population-attributable risk from abdominal obesity and diabetes. Use Framingham as a starting point but apply clinical judgment for Indian patients."),
    ("What modifies Framingham risk score?", "Risk-enhancing factors that increase effective risk beyond calculated score: family history of premature ASCVD (men <55, women <65), high-sensitivity CRP ≥2 mg/L, lipoprotein(a) ≥50 mg/dL, ABI <0.9, metabolic syndrome, chronic inflammatory conditions (RA, psoriasis, HIV), and chronic kidney disease. These factors support earlier or more intensive statin therapy in intermediate-risk patients."),
    ("What lifestyle changes reduce cardiovascular risk?", "Smoking cessation (most impactful — halves CV risk within 1 year), Mediterranean/DASH diet, aerobic exercise (150 min/week moderate intensity), weight loss (5–10% reduces multiple risk factors), optimal BP control (<130/80 mmHg), and glycaemic control in diabetes (HbA1c <7%). Combined, these reduce 10-year Framingham risk by 30–50%."),
    ("When should a statin be started based on Framingham risk?", "High risk (>20%): high-intensity statin (atorvastatin 40-80 mg or rosuvastatin 20-40 mg). Intermediate risk (10-20%): moderate-to-high intensity statin recommended. Low-intermediate (7.5-10%): statin should be considered, especially with risk-enhancing factors. Low risk (<7.5%): lifestyle modification first; statin if LDL remains ≥160 mg/dL. Always combine with lifestyle intervention."),
],
"grace-score": [
    ("What is the GRACE score used for?", "The GRACE (Global Registry of Acute Coronary Events) score predicts in-hospital and 6-month mortality in patients with acute coronary syndrome (ACS — both NSTEMI and STEMI). It uses 8 variables: age, heart rate, systolic BP, creatinine, Killip class, cardiac arrest at admission, ST deviation, and elevated cardiac markers. Scores range 0–372."),
    ("How does GRACE score guide ACS management?", "GRACE in-hospital mortality: Low (<108): <1%. Intermediate (108–140): 1–3%. High (>140): >3%. For NSTEMI: high GRACE score (>140) indicates benefit from early invasive strategy (coronary angiography within 24 hours). Low GRACE score allows selective invasive approach. STEMI patients proceed to primary PCI regardless of GRACE score."),
    ("What is Killip classification in ACS?", "Killip class assesses heart failure severity in ACS: Class I — no heart failure signs. Class II — mild HF (S3 gallop, basal crepitations <50% of lung fields, raised JVP). Class III — pulmonary oedema. Class IV — cardiogenic shock (SBP <90 with hypoperfusion). Higher Killip class significantly increases GRACE score and 30-day mortality."),
    ("What is the initial management of NSTEMI?", "Dual antiplatelet therapy: aspirin 300 mg loading + ticagrelor 180 mg (preferred) or clopidogrel 300-600 mg. Anticoagulation: fondaparinux 2.5 mg SC OD (preferred if no PCI planned), or enoxaparin, or UFH if PCI planned within 24 hours. High-intensity statin (atorvastatin 80 mg). Beta-blocker if no contraindication. ACE inhibitor/ARB. Timing of angiography guided by GRACE score and clinical risk."),
    ("What biomarkers are elevated in ACS?", "High-sensitivity troponin I or T (hsTnI/hsTnT): most sensitive and specific — rises within 1-3 hours of myocardial injury, peaks at 12-24 hours. Serial troponins at 0h and 3h (ESC 0/3h algorithm) or 0h and 1h (0/1h algorithm) allow rapid rule-in/rule-out. CK-MB: less sensitive than troponin, useful for re-infarction detection. BNP/NT-proBNP: elevated with LV dysfunction — prognostic value."),
    ("What is the difference between GRACE and TIMI score?", "GRACE score (8 variables, continuous) is more accurate than TIMI for predicting mortality in NSTEMI — AUC ~0.84 vs ~0.65. TIMI (7 variables, simpler) was designed for risk of ischaemic events (death, MI, revascularisation) rather than mortality. ESC and most international guidelines recommend GRACE for NSTEMI risk stratification. TIMI is still used in some centres for its simplicity."),
],
"hunt-hess": [
    ("What is the Hunt-Hess scale?", "The Hunt-Hess scale grades clinical severity of subarachnoid haemorrhage (SAH) at presentation: Grade 1 — asymptomatic or mild headache/neck stiffness. Grade 2 — moderate to severe headache, nuchal rigidity, no neurological deficit except CN palsy. Grade 3 — drowsiness, confusion, mild focal deficit. Grade 4 — stupor, moderate-severe hemiparesis. Grade 5 — deep coma, decerebrate posturing, moribund."),
    ("How does Hunt-Hess grade predict outcome?", "Grade 1-2: good surgical candidates, 70-80% good outcome. Grade 3: moderate risk, 50-60% good outcome. Grade 4: high risk, 20-30% good outcome. Grade 5: very high risk, <10% good outcome, high surgical mortality. Grade guides timing of aneurysm securing — Grade 1-3 patients benefit from early intervention (within 24-72 hours); Grade 4-5 may require delayed intervention after clinical stabilisation."),
    ("What is the classic presentation of SAH?", "'Thunderclap headache' — sudden onset severe headache described as the worst headache of patient's life, reaching maximum intensity within seconds. Associated features: neck stiffness (meningism from blood in CSF), photophobia, nausea/vomiting, brief loss of consciousness at onset, focal neurological deficits (CN III palsy = posterior communicating artery aneurysm). Sentinel headache (warning bleed) may precede major SAH by days."),
    ("What investigations are done for SAH?", "CT head non-contrast (sensitivity >98% within 6 hours of ictus — hyperdense blood in basal cisterns). If CT negative but SAH suspected: lumbar puncture after 6 hours (xanthochromia on spectrophotometry, or >2000 RBCs in tube 4). CT angiography (CTA) for aneurysm identification — sensitivity >95%. Digital subtraction angiography (DSA) if CTA negative with high clinical suspicion."),
    ("What are the main complications of SAH?", "Rebleeding (highest risk first 24 hours — prevented by early aneurysm securing), cerebral vasospasm (days 3-14 — prevented by nimodipine 60 mg PO every 4 hours), hydrocephalus (acute — treated with EVD; chronic — VP shunt), hyponatraemia (cerebral salt wasting or SIADH), seizures, and cardiac complications (neurogenic stunned myocardium, ECG changes including QTc prolongation)."),
    ("How is aneurysmal SAH treated?", "Aneurysm securing: endovascular coiling (preferred if technically feasible — ISAT trial) or surgical clipping. Supportive care: nimodipine 60 mg PO/NG 4-hourly for 21 days (reduces vasospasm), maintain euvolaemia (avoid hypovolaemia — worsens vasospasm), euglycaemia, normothermia, treat hydrocephalus. Blood pressure management: pre-securing maintain SBP <160 mmHg to reduce rebleed risk."),
],
"hypothyroidism": [
    ("What are the symptoms of hypothyroidism?", "Classic symptoms: fatigue and lethargy (most common), weight gain, cold intolerance, constipation, dry skin and hair, hair loss, bradycardia, myalgia, depression, cognitive slowing ('brain fog'), menstrual irregularity (heavy periods), and facial puffiness (periorbital oedema). In severe hypothyroidism: myxoedema — non-pitting oedema, hoarse voice, carpal tunnel syndrome, pleural/pericardial effusions, and ultimately myxoedema coma."),
    ("What is the most common cause of hypothyroidism in India?", "Hashimoto thyroiditis (autoimmune thyroiditis) is the most common cause in iodine-sufficient urban India, characterised by elevated anti-TPO and anti-thyroglobulin antibodies and lymphocytic infiltration of the thyroid. Iodine deficiency remains a significant cause in remote and hilly regions (Himalayan belt, northeast India) where iodised salt use is suboptimal. Iatrogenic causes: post-thyroidectomy and post-radioiodine ablation for hyperthyroidism."),
    ("What is the starting dose of levothyroxine?", "Standard dose: 1.6 mcg/kg/day actual body weight in young healthy adults. Elderly (>65 years) or ischaemic heart disease: start low at 12.5–25 mcg/day, uptitrate by 12.5–25 mcg every 6–8 weeks. Severe hypothyroidism or myxoedema coma: IV levothyroxine 200–500 mcg stat (hospital setting) + exclude adrenal insufficiency before giving T4. Recheck TSH after 6–8 weeks of any dose change."),
    ("What TSH level confirms hypothyroidism?", "Overt hypothyroidism: TSH >10 mIU/L with low free T4 — always treat. Subclinical hypothyroidism: TSH 4–10 mIU/L with normal free T4. Treat subclinical if: TSH >10, symptoms present, positive anti-TPO antibodies, pregnant or planning pregnancy, or age <65 with cardiovascular risk factors. Do not routinely treat asymptomatic TSH 4–10 in elderly >65 — TRUST trial showed no benefit."),
    ("How is levothyroxine taken correctly?", "Take on an empty stomach 30–60 minutes before breakfast (or at bedtime, consistently). Calcium supplements, iron tablets, PPIs, and antacids reduce levothyroxine absorption — take 4 hours apart. Drug interactions increasing T4 requirement: rifampicin, phenytoin, carbamazepine. Consistency in timing and brand matters — avoid switching brands without TSH monitoring. Recheck TSH 6–8 weeks after any dose change; annually when stable."),
    ("What is myxoedema coma?", "Myxoedema coma is a life-threatening complication of severe untreated hypothyroidism: hypothermia, bradycardia, hypotension, hypoventilation, altered consciousness, and hyponatraemia. Precipitants: cold exposure, infection, sedatives, surgery. Management: IV levothyroxine 200–500 mcg stat (penetrates blood-brain barrier faster) ± IV T3, IV hydrocortisone (adrenal insufficiency may co-exist), rewarming, supportive ICU care. Mortality 20–50% even with treatment."),
],
"lab-unit-converter": [
    ("Why are different units used for the same lab test?", "Laboratory units vary by country and historical convention. The SI system (Système International) uses molar units (mmol/L, µmol/L) preferred in Europe, Australia, and Canada. Conventional units (mg/dL, g/dL, mEq/L) are used in the USA, India, and much of Asia. Both systems are valid — the conversion factor depends on the molecular weight of the substance being measured."),
    ("How do I convert mg/dL to mmol/L?", "mmol/L = mg/dL ÷ (molecular weight / 10). For glucose: MW = 180, so 1 mmol/L = 18 mg/dL (glucose 126 mg/dL = 7.0 mmol/L). For creatinine: MW = 113, so 1 mg/dL = 88.4 µmol/L. For urea: MW = 60, so 1 mg/dL urea = 0.357 mmol/L (but BUN uses nitrogen MW = 28, so 1 mg/dL BUN = 0.714 mmol/L urea)."),
    ("What is the difference between BUN and serum urea?", "BUN (Blood Urea Nitrogen) measures only the nitrogen component of urea (MW 28), while serum urea measures the whole urea molecule (MW 60). BUN is used in the USA and India (mg/dL). Serum urea in mmol/L is used in UK/Europe. Conversion: Urea (mmol/L) = BUN (mg/dL) × 0.357; or BUN (mg/dL) = Urea (mmol/L) × 2.8. Normal BUN: 7–20 mg/dL; Normal serum urea: 2.5–7.1 mmol/L."),
    ("How is HbA1c converted between % and mmol/mol?", "DCCT % to IFCC mmol/mol: mmol/mol = (HbA1c% − 2.15) × 10.929. Example: HbA1c 7% = (7 − 2.15) × 10.929 = 53 mmol/mol. Reverse: HbA1c% = (mmol/mol ÷ 10.929) + 2.15. India uses DCCT % (ADA/RSSDI guidelines). UK/Europe use IFCC mmol/mol. Most modern lab analysers report both."),
    ("What are common unit conversion errors in clinical practice?", "Dangerous errors: confusing mg/dL and mmol/L for glucose (factor of 18 — misreading 18 mmol/L as 18 mg/dL would be life-threatening); confusing BUN and urea values (factor of 2.8); confusing µg/mL and µg/dL for drug levels (factor of 100); and confusing ng/mL and ng/dL for hormones (factor of 100). Always check units when receiving results from a different laboratory system."),
    ("How do I convert cholesterol and lipid units?", "Total cholesterol, LDL, HDL: mg/dL × 0.0259 = mmol/L. Example: LDL 130 mg/dL = 3.37 mmol/L. Triglycerides: mg/dL × 0.0113 = mmol/L. Example: TG 150 mg/dL = 1.70 mmol/L. Indian labs report in mg/dL. UK/Europe use mmol/L. ATP III/AHA targets are in mg/dL; ESC/EAS targets are in mmol/L — always check which system the guideline uses."),
],
"ldl-calculator": [
    ("What is the Friedewald formula for LDL?", "LDL cholesterol (mg/dL) = Total Cholesterol − HDL − (Triglycerides / 5). This is valid only when fasting triglycerides are <400 mg/dL. In SI units: LDL (mmol/L) = Total Cholesterol − HDL − (Triglycerides / 2.2). The formula underestimates LDL at high triglyceride levels — use direct LDL measurement if TG >400 mg/dL."),
    ("What is the LDL target for cardiovascular risk reduction?", "ACC/AHA and ESC guidelines: Very high risk (established CVD, DM with organ damage): LDL <55 mg/dL (<1.4 mmol/L). High risk (DM without organ damage, 10-year risk >10%): LDL <70 mg/dL (<1.8 mmol/L). Moderate risk: LDL <100 mg/dL (<2.6 mmol/L). Low risk: LDL <116 mg/dL (<3.0 mmol/L). More aggressive targets are recommended after recent ACS."),
    ("Which statin achieves the most LDL reduction?", "High-intensity statins: atorvastatin 40–80 mg (reduces LDL ~50%) or rosuvastatin 20–40 mg (reduces LDL ~55%). Moderate-intensity: atorvastatin 10–20 mg, rosuvastatin 5–10 mg, simvastatin 20–40 mg (reduces LDL ~30–50%). Each doubling of statin dose reduces LDL by an additional ~6% ('rule of 6'). If LDL target not achieved: add ezetimibe (further ~20% reduction) before escalating to PCSK9 inhibitors."),
    ("When is the Friedewald formula inaccurate?", "Inaccurate when: TG >400 mg/dL (severely hypertriglyceridaemic), TG <150 mg/dL (underestimates LDL), in type III hyperlipidaemia (dysbetalipoproteinaemia), in non-fasting samples. In these situations, use direct LDL measurement by laboratory or the Sampson-NIH equation which is more accurate at extremes of TG and LDL values."),
    ("What is non-HDL cholesterol and when is it useful?", "Non-HDL cholesterol = Total Cholesterol − HDL. It includes all atherogenic lipoproteins (LDL, VLDL, IDL, Lp(a)) and is a better predictor of CVD risk than LDL alone, particularly in patients with hypertriglyceridaemia or diabetes. Non-HDL targets are typically 30 mg/dL higher than LDL targets. Non-HDL cholesterol does not require fasting and can be calculated from a random sample — useful in population screening."),
    ("Are statins safe long-term?", "Statins are among the most studied drugs in medicine. Proven safe for long-term use in the vast majority. Main adverse effects: myalgia (5–10%, often non-specific), myositis with elevated CK (rare, <0.1%), rhabdomyolysis (very rare, 1–3 per 100,000). Slight increase in diabetes risk (~10% relative increase). No credible evidence for cognitive impairment or cancer risk. Routine monitoring: LFTs only if symptomatic; CK only if myalgia. Benefits far outweigh risks in patients with CVD risk."),
],
"nihss-calculator": [
    ("What does the NIHSS measure?", "The NIH Stroke Scale (NIHSS) quantifies neurological deficit severity in acute stroke using 11 items: level of consciousness (3 items), gaze, visual fields, facial palsy, motor arm (both), motor leg (both), limb ataxia, sensory, language/aphasia, dysarthria, and extinction/inattention. Score 0–42. Higher scores indicate more severe deficit."),
    ("How is NIHSS severity classified?", "NIHSS 0: no deficit. 1–4: minor stroke. 5–15: moderate stroke. 16–20: moderate-severe. 21–42: severe stroke. NIHSS >25 is associated with very poor outcome without reperfusion therapy. NIHSS >22 is a relative contraindication to IV thrombolysis in some guidelines due to high haemorrhagic transformation risk."),
    ("What NIHSS score qualifies for IV thrombolysis?", "IV alteplase (tPA) for ischaemic stroke: onset within 4.5 hours, NIHSS ≥4 (some centres treat NIHSS 1–3 with disabling deficits), NIHSS ≤25 (relative contraindication if >25). Contraindications include haemorrhage on CT, recent surgery, anticoagulation with therapeutic INR, and prior stroke + DM combination. MRI-guided thrombolysis can extend window in wake-up strokes."),
    ("What is mechanical thrombectomy and who is eligible?", "Mechanical thrombectomy (MT) removes large vessel occlusion (LVO) using catheter-based devices. Indicated for: large anterior circulation LVO (ICA, M1, M2 MCA) within 6 hours of onset (or 24 hours in DAWN/DEFUSE-3 criteria with mismatch imaging), NIHSS ≥6, and salvageable brain tissue on CT/MRI perfusion. MT is the most effective stroke treatment — NNT ~2.5 for functional independence. Available in comprehensive stroke centres in Indian metros."),
    ("How is NIHSS used for stroke prognosis?", "NIHSS at 24 hours better predicts outcome than admission NIHSS. NIHSS improvement of ≥4 points at 24 hours ('early neurological improvement') predicts good 90-day outcome after thrombolysis. Discharge NIHSS 0–1 correlates with excellent functional recovery (mRS 0–1). NIHSS is also used to assess eligibility for rehabilitation services and to track recovery trajectory."),
    ("What is the difference between NIHSS and mRS?", "NIHSS measures neurological deficit at a point in time — useful for acute assessment and treatment decisions. mRS (modified Rankin Scale) measures functional disability and independence — used for outcome assessment at 90 days. They measure different domains: NIHSS captures neurological findings; mRS captures functional impact on daily life. A patient can have a low NIHSS but high mRS if their deficit (e.g. isolated aphasia) severely impacts function."),
],
"pediatric-dehydration": [
    ("How is dehydration severity classified in children?", "Mild (<5% body weight loss): no clinical signs, alert, normal pulse/BP/capillary refill, eyes normal, moist mucous membranes. Moderate (5–10%): restless/irritable, tachycardia, reduced skin turgor, sunken eyes/fontanelle, dry mucous membranes, capillary refill 2–3 seconds. Severe (>10%): lethargic/unconscious, absent pulses, cold peripheries, capillary refill >3 seconds, deeply sunken eyes — shock, immediate IV resuscitation required."),
    ("What is the WHO ORS plan for rehydration?", "Plan A (no/mild dehydration): 10 mL/kg ORS after each loose stool at home. Plan B (some dehydration 5–10%): 75 mL/kg ORS over 4 hours in ORT corner, reassess. Plan C (severe dehydration): IV Ringer's Lactate 100 mL/kg — for infants: 30 mL/kg in 1 hour then 70 mL/kg in 5 hours; for older children: 30 mL/kg in 30 min then 70 mL/kg in 2.5 hours. Switch to ORS when able to drink."),
    ("What IV fluid is used for paediatric rehydration?", "Ringer's Lactate (Hartmann's solution) is preferred over 0.9% normal saline for large-volume resuscitation in children — reduces hyperchloraemic acidosis risk. 0.9% saline with 5% dextrose is the standard maintenance fluid (not hypotonic solutions which cause hyponatraemia). Avoid dextrose-containing fluids for resuscitation boluses. Add KCl 20 mmol/L to maintenance once the child is urinating."),
    ("How is oral rehydration therapy given?", "Give ORS in small, frequent sips using a spoon or cup — not a bottle. If the child vomits, wait 10 minutes then resume at slower rate (5 mL every 1–2 minutes). Continue breastfeeding throughout. Start age-appropriate foods after 4 hours of ORS in Plan B. Zinc supplementation 10–20 mg/day for 10–14 days alongside ORS reduces duration and recurrence of diarrhoea."),
    ("What are the signs of hypernatraemic dehydration?", "Hypernatraemic dehydration (Na >150 mEq/L) occurs with water loss > sodium loss — typically in breastfed neonates with poor intake, or diarrhoea with high sodium ORS. Signs: doughy/thick skin turgor (paradoxically less obvious dehydration signs), irritability, high-pitched cry, fever, seizures (risk with rapid correction). Correct slowly — rehydrate over 48 hours targeting Na fall of <10–12 mEq/L/day to prevent cerebral oedema."),
    ("When should a child with diarrhoea be admitted?", "Admit if: severe dehydration or shock, unable to tolerate oral fluids/ORS despite attempts, persistent vomiting (>3 times/hour), bloody diarrhoea with systemic illness (HUS risk), altered consciousness, age <3 months with any dehydration, hypoglycaemia (BGL <54 mg/dL), and social circumstances preventing safe home management. All severe dehydration requires IV access and hospital admission."),
],
"pediatric-weight": [
    ("What is the APLS formula for paediatric weight estimation?", "For children 1–10 years: Weight (kg) = 2 × (Age in years + 4). Example: 6-year-old = 2 × (6+4) = 20 kg. Alternative APLS formula: Weight = (Age + 4) × 2. For infants 3–12 months: Weight (kg) = (Age in months + 9) / 2. These are emergency estimates — actual weight should be measured when possible."),
    ("Why is accurate weight estimation important in children?", "Paediatric drug doses, IV fluid rates, resuscitation drug doses (adrenaline 0.01 mg/kg), defibrillation energy (4 J/kg), endotracheal tube size (age/4 + 4 mm), and tidal volume settings on ventilator are all weight-based. An error of 20% in weight estimation can mean a 20% drug dose error — potentially fatal for high-alert drugs like adrenaline, potassium, or suxamethonium."),
    ("What other methods estimate paediatric weight?", "Broselow tape: colour-coded tape based on child's height correlates to weight — most validated emergency weight estimation tool, includes pre-calculated drug doses by colour zone. PAWPER XL tape: improved accuracy in obese children. Parental estimation: parents usually accurate within 10%. Habitus-modified Broselow (PAWPER): adjusts for body habitus. WHO weight-for-age tables: gold standard for nutritional assessment but requires charts."),
    ("What is the normal weight gain pattern in infancy?", "Birth weight doubles by 4–5 months and triples by 12 months. Expected weight gain: 0–3 months: ~25–30 g/day; 3–6 months: ~15–20 g/day; 6–12 months: ~10–15 g/day. A neonate loses 5–10% of birth weight in first week (physiological) and regains it by day 10–14. Failure to regain birth weight by day 14 requires investigation (breastfeeding assessment, infection, metabolic)."),
    ("What weight indicates moderate acute malnutrition in Indian children?", "Using WHO/IAP standards: Weight-for-height Z-score <-2 to -3 = moderate acute malnutrition (MAM). Weight-for-height Z-score <-3 = severe acute malnutrition (SAM). In India, MUAC (mid-upper arm circumference) is also used: MUAC <11.5 cm = SAM in children 6–59 months; 11.5–12.5 cm = MAM. SAM with complications (oedema, medical complications) requires inpatient NRC (Nutrition Rehabilitation Centre) admission."),
    ("How is paediatric drug dosing different from adult dosing?", "Children are not small adults — drug metabolism, distribution, and elimination differ significantly by age. Neonates have immature hepatic and renal function (lower clearance). Drug distribution differs (higher total body water in infants). Always calculate dose per kg and compare against maximum adult dose — never exceed it. Use paediatric formularies (IAP drug handbook, BNFc) rather than extrapolating adult doses. Double-check all paediatric calculations independently."),
],
"perc-rule": [
    ("What is the PERC rule?", "The PERC (Pulmonary Embolism Rule-out Criteria) rule is used to exclude PE without further testing in very low-risk patients. All 8 criteria must be absent: age ≥50, HR ≥100, SpO2 <95% on room air, unilateral leg swelling, haemoptysis, recent surgery/trauma (within 4 weeks), prior PE/DVT, and oestrogen use. If ALL absent in a low pre-test probability patient: PE excluded without D-dimer or imaging."),
    ("When can PERC be applied?", "PERC is valid ONLY when pre-test probability is low (<15% — 'PE unlikely' by clinical gestalt or Wells score ≤4). Do NOT apply PERC in intermediate or high pre-test probability patients. In low-probability patients who are PERC-negative, the post-test probability of PE is <2% — below the threshold that justifies further testing or anticoagulation risk."),
    ("What is the PERC-Wells algorithm?", "Step 1: Calculate Wells score. If >4 (PE likely): go straight to CTPA. If ≤4 (PE unlikely): Step 2 — apply PERC. If PERC negative (all 8 absent): PE excluded, no further testing. If PERC positive (any criterion present): Step 3 — D-dimer (age-adjusted threshold if >50 years: age × 10 µg/L). If D-dimer negative: PE excluded. If positive: CTPA."),
    ("What is age-adjusted D-dimer?", "Standard D-dimer threshold is 500 µg/L for all adults. Age-adjusted threshold (for patients >50 years): Age × 10 µg/L. Example: 70-year-old — threshold = 700 µg/L. This reduces false-positive rates in elderly patients (D-dimer rises with age, inflammation, pregnancy, malignancy) without missing significant PEs. Validated in multiple studies; endorsed by ESC guidelines."),
    ("What are the most common PE symptoms?", "Dyspnoea (most common, ~80%), pleuritic chest pain (~50%), cough (~40%), haemoptysis (~15%), pre-syncope/syncope (~10%). Massive PE: haemodynamic instability, hypotension, tachycardia, RV strain on ECG (S1Q3T3, new RBBB, sinus tachycardia). Many PEs are clinically silent — discovered incidentally on CT. 'Silent hypoxia' (SpO2 drop without dyspnoea) is characteristic of COVID-19-associated PE."),
    ("What is the treatment of sub-massive PE?", "Sub-massive (intermediate-high risk) PE: haemodynamically stable but with RV dysfunction (RV:LV ratio >0.9 on CT or echo) AND elevated troponin. Treatment: anticoagulation (DOAC preferred — rivaroxaban or apixaban at treatment doses), close monitoring for haemodynamic deterioration. Systemic thrombolysis is not routinely indicated in stable patients but should be immediately available if clinical deterioration occurs. Consider catheter-directed thrombolysis in experienced centres."),
],
"qtc-calculator": [
    ("What is QTc and why is it important?", "QTc (corrected QT interval) adjusts the measured QT interval for heart rate, since QT naturally shortens at faster rates. A prolonged QTc indicates delayed ventricular repolarisation, which increases the risk of Torsades de Pointes (TdP) — a potentially fatal polymorphic ventricular tachycardia that can degenerate into ventricular fibrillation."),
    ("What is a normal QTc interval?", "Normal QTc: <440 ms in men, <450 ms in women. Borderline prolonged: 440–470 ms (men), 450–480 ms (women). Prolonged: >470 ms (men), >480 ms (women). Critical/high TdP risk: >500 ms in either sex. The female sex has an inherently longer QTc and higher TdP risk than males at equivalent QTc values."),
    ("Which drugs commonly prolong QTc?", "Common culprits in Indian clinical practice: antipsychotics (haloperidol, quetiapine, risperidone), antiemetics (metoclopramide, ondansetron, domperidone), antibiotics (azithromycin, ciprofloxacin, levofloxacin, clarithromycin), antifungals (fluconazole), antiarrhythmics (amiodarone, sotalol), antimalarials (chloroquine, hydroxychloroquine), antidepressants (TCAs). Check CredibleMeds (AZsert.com) for complete up-to-date list."),
    ("What electrolyte abnormalities prolong QTc?", "Hypokalaemia (most important — potassium stabilises cardiac membrane; low K prolongs repolarisation), hypomagnesaemia (often co-exists with hypokalaemia), and hypocalcaemia all prolong QTc. Always correct electrolytes before administering QT-prolonging drugs. Target K >4.0 mEq/L and Mg >0.8 mmol/L in patients at risk of TdP (known long QT, receiving QT-prolonging drugs)."),
    ("What is Torsades de Pointes and how is it treated?", "TdP is a polymorphic VT with characteristic twisting of QRS complexes around the isoelectric line, occurring in the setting of prolonged QTc. It may self-terminate or degenerate to VF. Treatment: IV magnesium sulphate 2 g bolus (first-line regardless of Mg level), temporary cardiac pacing or isoproterenol to increase heart rate (shortens QT), withdraw offending drug, correct electrolytes, defibrillation if degenerates to VF. Avoid class IA/IC antiarrhythmics."),
    ("What formulas are used to calculate QTc?", "Bazett formula: QTc = QT / √RR (most widely used, tends to overcorrect at fast rates). Fridericia formula: QTc = QT / RR^0.333 (more accurate at extremes of HR). Hodges formula: QTc = QT + 1.75 × (HR − 60). Bazett is standard on ECG machines but overestimates QTc at HR >100. Fridericia is preferred in tachycardia. Measure QT in lead II or V5 from Q wave onset to T wave end."),
],
"rass-score": [
    ("What is the RASS scale?", "The Richmond Agitation-Sedation Scale (RASS) assesses level of sedation and agitation in ICU patients. Scores: +4 Combative (violent), +3 Very agitated (pulls lines), +2 Agitated (purposeless movement), +1 Restless (anxious, not aggressive), 0 Alert and calm, -1 Drowsy (eyes open briefly to voice), -2 Light sedation (eyes open <10 sec to voice), -3 Moderate sedation (movement to voice, no eye contact), -4 Deep sedation (movement to physical stimulus only), -5 Unarousable."),
    ("What is the target RASS in mechanically ventilated patients?", "SCCM/PADIS guidelines recommend targeting RASS 0 to -2 (light sedation) for most mechanically ventilated ICU patients. Light sedation is associated with shorter duration of mechanical ventilation, shorter ICU stay, and better cognitive outcomes compared to deep sedation (RASS -3 to -5). Deep sedation should be avoided unless specifically indicated (status epilepticus, severe ARDS on paralysis, elevated ICP)."),
    ("How is RASS used for delirium assessment?", "RASS is the prerequisite for delirium assessment using CAM-ICU (Confusion Assessment Method for ICU). CAM-ICU can only be performed when RASS is ≥-3. If RASS is -4 or -5 (unarousable/deeply sedated), delirium cannot be assessed — document as 'unable to assess' and aim to reduce sedation. Delirium assessment should be performed every 8-12 hours in all ICU patients."),
    ("What sedation agents are used in ICU?", "Preferred agents (SCCM/PADIS guidelines): propofol (short-acting, easy to titrate, allows rapid awakening, lipid-based — monitor triglycerides) or dexmedetomidine (alpha-2 agonist, preserves arousability, reduces delirium, no respiratory depression — preferred for light sedation). Midazolam (benzodiazepine) is associated with more delirium and longer ICU stay — avoid for routine sedation. Ketamine useful as adjunct analgesic-sedative, especially in bronchospasm."),
    ("What is the ABCDEF bundle in ICU?", "The ICU Liberation ABCDEF bundle: A — Assess, prevent, manage pain. B — Spontaneous Breathing Trial (daily SAT + SBT). C — Choice of analgesia/sedation (opioid-sparing, light sedation target). D — Delirium assessment and management (CAM-ICU, treat causes). E — Early mobility and Exercise. F — Family engagement and empowerment. Bundle implementation reduces ICU mortality, duration of mechanical ventilation, and delirium prevalence."),
    ("What causes agitation in ICU patients?", "Common causes of agitation (RASS +1 to +4): pain (most common — assess with CPOT or NRS), delirium (hyperactive type), ventilator dysynchrony, urinary retention, constipation, anxiety, drug withdrawal (alcohol, benzodiazepines, opioids), hypoxia, hypercapnia, hypoglycaemia, and ICU psychosis. Always identify and treat the underlying cause before escalating sedation — adding more sedation to an agitated patient without addressing the cause worsens outcomes."),
],
"serum-osmolality": [
    ("What is serum osmolality and how is it calculated?", "Serum osmolality estimates the concentration of all osmotically active particles in plasma. Calculated formula: Osmolality (mOsm/kg) = 2 × Na + Glucose (mg/dL)/18 + BUN (mg/dL)/2.8. In SI units: 2 × Na + Glucose (mmol/L) + Urea (mmol/L). Normal range: 275–295 mOsm/kg. Measured osmolality by freezing-point depression is the gold standard."),
    ("What is the osmol gap and what causes it?", "Osmol gap = Measured osmolality − Calculated osmolality. Normal osmol gap: <10 mOsm/kg. An elevated osmol gap (>10–15) indicates unmeasured osmoles in plasma — caused by: toxic alcohols (methanol, ethylene glycol, isopropanol — most important causes), severe lactic acidosis, ketoacidosis (acetone), mannitol infusion, or propylene glycol toxicity. A high osmol gap in a comatose patient should immediately raise suspicion for toxic alcohol ingestion."),
    ("What causes hyperosmolaemia?", "Hyperosmolaemia (>295 mOsm/kg): hypernatraemia (sodium is the main determinant), severe hyperglycaemia (diabetic hyperosmolar state — serum osmolality can exceed 320–340 mOsm/kg), uraemia (BUN contributes but is an ineffective osmole — crosses cell membranes freely), toxic alcohol ingestion (effective osmoles — cause cellular dehydration). Hyperosmolar hyperglycaemic state (HHS): osmolality >320, glucose >600 mg/dL, no significant ketosis."),
    ("What is effective vs ineffective osmolality?", "Effective osmolality (tonicity) = 2 × Na + Glucose/18. It excludes BUN because urea freely crosses cell membranes and does not cause osmotic water shifts between compartments. Tonicity determines cellular hydration status and is clinically more relevant than total osmolality. Normal tonicity: 275–290 mOsm/kg. Hypertonicity causes cellular dehydration (brain shrinkage, cerebral haemorrhage risk)."),
    ("How is hyperosmolar hyperglycaemic state managed?", "HHS management: IV fluid resuscitation (0.9% saline initially — typically 1–2L in first hour, then 0.45% saline if Na corrected or normal), low-dose insulin infusion (only after adequate hydration — insulin without fluids worsens hypotension), potassium replacement (severe hypokalaemia risk as glucose normalises), VTE prophylaxis (high thrombosis risk), treat precipitant (infection most common). Target: gradual glucose reduction ~50–70 mg/dL/hour, osmolality reduction <3 mOsm/kg/hour."),
    ("What is SIADH and how does serum osmolality help diagnose it?", "SIADH (Syndrome of Inappropriate ADH secretion) causes euvolaemic hyponatraemia with: serum osmolality <275 mOsm/kg, urine osmolality >100 mOsm/kg (inappropriately concentrated), urine sodium >20–40 mEq/L (sodium-wasting despite hyponatraemia), normal renal, adrenal, and thyroid function. Causes: CNS disease, pulmonary disease, malignancy (ectopic ADH), drugs (SSRIs, carbamazepine, cyclophosphamide, NSAIDs). Treatment: fluid restriction ±salt tablets; tolvaptan for severe/refractory cases."),
],
"shock-index": [
    ("What is the shock index?", "Shock Index (SI) = Heart Rate / Systolic Blood Pressure. Normal SI: 0.5–0.7. SI >1.0 indicates haemodynamic compromise — the heart rate exceeds systolic BP, reflecting compensated or overt shock. SI >1.4 correlates with severe haemorrhage and massive transfusion requirement. It is a simple bedside tool requiring only pulse oximetry and BP measurement."),
    ("How is shock index used in trauma?", "In trauma: SI >1.0 predicts the need for blood transfusion. SI >1.4–1.5: high likelihood of massive transfusion protocol (MTP) activation (≥10 units pRBCs in 24 hours). In obstetric haemorrhage: SI >0.9 predicts severe postpartum haemorrhage. In UGIB: SI >1.0 is a red flag for major bleed requiring urgent endoscopy. SI is particularly useful when exact blood loss is unknown."),
    ("What are the types of shock?", "Hypovolaemic (most common): haemorrhage, burns, dehydration — high SI, cold peripheries, collapsed veins. Distributive (septic, anaphylactic, neurogenic): SI >1 early (vasodilation), warm peripheries in early sepsis. Cardiogenic: SI >1, cold peripheries, raised JVP, pulmonary oedema, S3 gallop. Obstructive (PE, tamponade, tension pneumothorax): SI >1, specific clinical signs. Each type requires different immediate management."),
    ("What are the initial steps in managing shock?", "ABCDE approach: Airway — ensure patent. Breathing — high-flow O2 (15L via non-rebreather mask). Circulation — large-bore IV access ×2, blood cultures, urgent bloods (FBC, coag, crossmatch, lactate, ABG), IV fluid bolus 250–500 mL crystalloid and reassess (avoid fluid overload in cardiogenic shock). Disability — GCS, glucose. Exposure — identify source. Activate massive transfusion protocol if haemorrhagic shock with SI >1.4."),
    ("When does shock index fail?", "Shock index is less reliable in: elderly patients (chronotropic incompetence — cannot mount appropriate tachycardia; beta-blockers blunt HR response), patients on vasopressors (BP maintained artificially), and neurogenic shock (paradoxical bradycardia with hypotension — SI may be normal or low despite severe haemodynamic compromise). Always interpret SI alongside clinical assessment, lactate, and urine output."),
    ("What is the modified shock index?", "Modified Shock Index (MSI) = HR / Mean Arterial Pressure. Normal MSI: 0.7–1.1. MSI >1.4 predicts in-hospital mortality in sepsis and trauma better than SI alone. MSI incorporates diastolic BP which SI ignores, making it more sensitive for early shock detection. However, both SI and MSI are screening tools — neither replaces comprehensive haemodynamic assessment."),
],
"sodium-correction": [
    ("What is the corrected sodium formula in hyperglycaemia?", "Hyperglycaemia causes osmotic shift of water from cells into plasma, diluting sodium. Corrected Na = Measured Na + 2.4 × [(Glucose − 100) / 100] (glucose in mg/dL). Alternative (more accurate for severe hyperglycaemia): Corrected Na = Measured Na + 1.6 × [(Glucose − 100) / 100]. If corrected Na is high (>145 mEq/L) despite apparent hyponatraemia, the patient is actually hypernatraemic — true sodium deficit is masked by glucose dilution."),
    ("What is the correction rate for hyponatraemia?", "Chronic hyponatraemia (>48 hours or unknown duration): correct sodium at maximum 10–12 mEq/L per 24 hours (or 8 mEq/L/24h if high risk of osmotic demyelination — alcoholism, malnutrition, hypokalaemia, liver disease). Correction faster than this risks osmotic demyelination syndrome (ODS) — a potentially fatal pontine and extrapontine demyelination causing paraplegia, dysarthria, and locked-in syndrome."),
    ("What is osmotic demyelination syndrome?", "ODS (formerly central pontine myelinolysis) occurs when chronic hyponatraemia is corrected too rapidly. Brain cells that have adapted to low sodium by losing osmolytes are suddenly exposed to rapid osmolality change, causing myelin sheath destruction. Onset 2–6 days after overcorrection. Symptoms: pseudobulbar palsy, spastic quadriplegia, dysarthria, dysphagia, altered consciousness. Prevention: strict rate limit of ≤10–12 mEq/L/24h, and re-lowering sodium with dextrose water + desmopressin if overcorrection occurs."),
    ("How is acute symptomatic hyponatraemia treated?", "Acute severe hyponatraemia (seizures, coma, severe symptoms): 3% hypertonic saline 100–150 mL IV over 20 minutes, repeat once or twice until symptoms resolve. Target: raise Na by 4–6 mEq/L rapidly to stop acute brain herniation, then switch to controlled correction (≤10 mEq/L/day). This is an emergency — do not apply chronic hyponatraemia correction limits in acute symptomatic cases."),
    ("What are the common causes of hyponatraemia in India?", "Most common causes seen in Indian hospitals: SIADH (secondary to CNS infections — TB meningitis and bacterial meningitis are major causes in India, also pneumonia, post-neurosurgery), excessive hypotonic IV fluids (iatrogenic — especially in postoperative patients given large volumes of 5% dextrose), hypothyroidism, adrenal insufficiency (Addison's disease, post-steroid withdrawal), decompensated liver cirrhosis, and nephrotic syndrome."),
    ("How is hypernatraemia managed?", "Hypernatraemia (Na >145 mEq/L): identify and treat cause (inadequate water intake, diabetes insipidus, excessive sodium load). Free water deficit = 0.6 × weight × [(Na/140) − 1]. Replace deficit with oral water (preferred) or IV 5% dextrose or 0.45% saline. Correction rate: no faster than 10–12 mEq/L/day for chronic hypernatraemia (risk of cerebral oedema with rapid correction). Monitor Na every 4–6 hours during active correction."),
],
"sofa-score": [
    ("What does each SOFA component measure?", "Respiratory: PaO2/FiO2 ratio (P/F ratio). Coagulation: platelet count. Liver: serum bilirubin. Cardiovascular: MAP and vasopressor dose (dopamine, dobutamine, adrenaline, noradrenaline). Neurological: Glasgow Coma Scale. Renal: serum creatinine or urine output. Each component scored 0–4 (0=normal, 4=most abnormal). Total score 0–24."),
    ("How does SOFA define sepsis?", "Sepsis-3 (Singer et al., JAMA 2016): Sepsis = life-threatening organ dysfunction caused by dysregulated host response to infection, identified by acute SOFA increase ≥2 from baseline. Septic shock = sepsis + vasopressor requirement to maintain MAP ≥65 mmHg AND lactate >2 mmol/L despite adequate fluids. The 'severe sepsis' category has been retired."),
    ("What is the mortality prediction of SOFA?", "Initial SOFA: 0–6 (~<10% ICU mortality), 7–9 (~15–20%), 10–12 (~40%), 13–14 (~50%), 15–24 (>80%). Change in SOFA over 48 hours is more predictive than initial score — rising SOFA despite treatment indicates treatment failure; falling SOFA indicates clinical response. A SOFA score increase of ≥2 from baseline in a ward patient with suspected infection has ~10% hospital mortality."),
    ("How is the cardiovascular SOFA scored?", "Cardiovascular SOFA: 0 = MAP ≥70 mmHg. 1 = MAP <70 mmHg. 2 = Dopamine ≤5 mcg/kg/min or any dobutamine. 3 = Dopamine 5–15 mcg/kg/min or adrenaline/noradrenaline ≤0.1 mcg/kg/min. 4 = Dopamine >15 mcg/kg/min or adrenaline/noradrenaline >0.1 mcg/kg/min. Higher vasopressor requirements indicate more severe cardiovascular failure."),
    ("When is SOFA used vs APACHE II?", "APACHE II: calculated once at ICU admission — admission severity score for benchmarking and prognosis at admission. SOFA: calculated daily — trajectory score for monitoring organ failure progression. Use APACHE II for 'how sick is this patient at admission?' Use SOFA for 'is this patient getting better or worse day by day?' Both are complementary. SOFA is also embedded in the Sepsis-3 definition."),
    ("What is the 1-hour sepsis bundle?", "Surviving Sepsis Campaign 1-hour bundle: measure lactate (repeat if >2 mmol/L), obtain blood cultures before antibiotics (≥2 sets), administer broad-spectrum IV antibiotics, give 30 mL/kg IV crystalloid if hypotensive or lactate ≥4 mmol/L, start vasopressors (noradrenaline first-line) if MAP <65 despite initial fluids. Bundle compliance reduces sepsis mortality by ~25%."),
],
"steroid-equivalence": [
    ("What is steroid equivalence?", "Steroid equivalence refers to the anti-inflammatory potency of different corticosteroids relative to hydrocortisone (reference = 1). Equivalent anti-inflammatory doses: hydrocortisone 20 mg = prednisolone 5 mg = methylprednisolone 4 mg = dexamethasone 0.75 mg = betamethasone 0.6 mg. Note: mineralocorticoid potency is separate — dexamethasone has negligible mineralocorticoid activity while hydrocortisone has significant fludrocortisone-like effects."),
    ("What is the difference between prednisolone and dexamethasone?", "Prednisolone: moderate potency (4–5x hydrocortisone), significant mineralocorticoid activity, half-life 12–36 hours, once or twice daily dosing, first-line for most chronic inflammatory conditions. Dexamethasone: high potency (25–30x hydrocortisone), negligible mineralocorticoid activity, half-life 36–72 hours, once daily dosing, preferred for: brain oedema, COVID-19 (RECOVERY trial), antenatal lung maturation, croup, antiemesis (chemotherapy), and acute spinal cord compression."),
    ("How should long-term steroids be tapered?", "Prolonged steroid use (>3 weeks at >5 mg prednisolone/day) suppresses the HPA axis — abrupt withdrawal can cause adrenal crisis (hypotension, hyponatraemia, hypoglycaemia, death). Taper by 10–20% every 1–2 weeks until physiological dose (prednisolone 5–7.5 mg/day), then slower taper. Physiological steroid dose is approximately prednisolone 5 mg/day (equivalent to cortisol production of 15–20 mg/day). Check morning cortisol before stopping completely."),
    ("What are the side effects of long-term steroid use?", "Metabolic: hyperglycaemia (steroid-induced DM), hyperlipidaemia, weight gain, moon face, buffalo hump, central obesity. Musculoskeletal: osteoporosis (DEXA scan + bisphosphonate prophylaxis if >3 months use), myopathy (proximal weakness — characteristic). Cardiovascular: hypertension, fluid retention. GI: peptic ulcer disease (especially with NSAIDs — PPI prophylaxis). Ophthalmic: posterior subcapsular cataracts, raised IOP/glaucoma. Endocrine: HPA suppression, growth retardation in children. Infection: increased susceptibility, reactivation of TB/strongyloides."),
    ("When are steroids used in critical care?", "Evidence-based ICU indications: septic shock refractory to vasopressors (hydrocortisone 200 mg/day IV — APROCCHSS trial), ARDS (dexamethasone 20 mg/day × 5 days then 10 mg × 5 days — DEXA-ARDS trial), COVID-19 requiring O2/ventilation (dexamethasone 6 mg/day × 10 days — RECOVERY trial), meningitis (dexamethasone 0.15 mg/kg QID × 4 days — reduces hearing loss in pneumococcal meningitis), anaphylaxis (hydrocortisone 200 mg IV), and acute spinal cord injury (controversial)."),
    ("What steroid is used for antenatal lung maturation?", "Betamethasone 12 mg IM × 2 doses 24 hours apart (or dexamethasone 6 mg IM × 4 doses 12 hours apart) given to the mother at 24–34 weeks gestation when preterm delivery is anticipated within 7 days. Reduces neonatal RDS, IVH, necrotising enterocolitis, and neonatal mortality by 30–50%. A single course is recommended — repeated courses (>2) are associated with reduced fetal growth and neurodevelopmental risk."),
],
"upcr-calculator": [
    ("What is the urine protein-to-creatinine ratio?", "The urine protein-to-creatinine ratio (UPCR) estimates 24-hour urine protein excretion from a spot urine sample. UPCR (mg/mg) numerically approximates 24-hour proteinuria in g/day. UPCR <0.15 mg/mg is normal. UPCR 0.15–3.5 = significant proteinuria. UPCR >3.5 mg/mg = nephrotic-range proteinuria (equivalent to >3.5 g/day)."),
    ("Why is UPCR preferred over 24-hour urine collection?", "24-hour urine collection is inconvenient, often inaccurately collected, and delays diagnosis. UPCR from a spot (preferably first morning void) sample correlates closely with 24-hour proteinuria and is reproducible. It is recommended by KDIGO guidelines as the standard method for proteinuria quantification in CKD monitoring. The first morning void minimises the effect of postural proteinuria."),
    ("What does nephrotic-range proteinuria indicate?", "UPCR >3.5 (or >3.5 g/day proteinuria) defines nephrotic syndrome when accompanied by: hypoalbuminaemia (<3.5 g/dL), oedema, and hyperlipidaemia/lipiduria. In adults, common causes include: membranous nephropathy (most common primary cause), minimal change disease (most common in children), focal segmental glomerulosclerosis (FSGS), diabetic nephropathy (most common secondary cause in India), amyloidosis, and lupus nephritis (class V)."),
    ("How is proteinuria monitored in CKD?", "KDIGO 2024 CKD classification uses albuminuria category (A1/A2/A3) combined with GFR stage. UPCR or UACR (albumin-creatinine ratio) at each clinic visit. UACR <30 mg/g = A1 (normal). UACR 30–300 = A2 (moderately increased). UACR >300 = A3 (severely increased). Worsening albuminuria category indicates CKD progression. ACE inhibitor or ARB reduces proteinuria and slows CKD progression in A2/A3 patients."),
    ("What causes false results in UPCR?", "False HIGH UPCR: contamination with blood (menstruation, haematuria), UTI (Tamm-Horsfall protein, pyuria), very concentrated urine. False LOW UPCR: very dilute urine (high fluid intake). Postural/orthostatic proteinuria (common in adolescents — UPCR elevated in upright position but normal in recumbent first morning void). Bence-Jones proteinuria (myeloma) is not detected by standard dipstick — requires urine protein electrophoresis (UPEP)."),
    ("What is the treatment of proteinuria in CKD?", "First-line: ACE inhibitor (ramipril, enalapril) or ARB (losartan, telmisartan) — reduce intraglomerular pressure and proteinuria by 30–50%, slow CKD progression. Target BP <130/80 mmHg. SGLT2 inhibitors (empagliflozin, dapagliflozin) provide additional renoprotection in CKD with proteinuria independent of diabetes. Finerenone (mineralocorticoid receptor antagonist) additionally reduces CKD progression in T2DM + CKD with UACR ≥30. Avoid NSAIDs, nephrotoxic drugs, and contrast in proteinuric CKD."),
],
"vitamin/k-calculator": [
    ("What does vitamin K do in the body?", "Vitamin K is a fat-soluble vitamin essential for the carboxylation of glutamate residues in clotting factors II, VII, IX, and X (pro-coagulant) and proteins C and S (anticoagulant), as well as osteocalcin (bone) and matrix Gla protein (vascular calcification prevention). It exists as K1 (phylloquinone — dietary, green vegetables) and K2 (menaquinone — gut bacteria, fermented foods, more important for bone/vascular health)."),
    ("What are the signs of vitamin K deficiency?", "Bleeding manifestations: easy bruising, prolonged bleeding from cuts, GI bleeding, haematuria, and intracranial haemorrhage (especially in neonates). Lab findings: prolonged PT/INR (factors II, VII, IX, X dependent on K), normal APTT (unless severe), normal platelet count and bleeding time. PIVKA-II (protein induced by vitamin K absence) is a sensitive marker of subclinical deficiency."),
    ("Who is at risk of vitamin K deficiency?", "Neonates (low placental transfer, sterile gut — all newborns receive prophylactic vitamin K at birth per NRP/NHM protocol: 1 mg IM at birth). Fat malabsorption syndromes (cholestatic liver disease, cystic fibrosis, coeliac disease, Crohn's). Prolonged antibiotic use (kills gut bacteria producing K2). Warfarin therapy (intentional K antagonism). Exclusively breastfed infants (breast milk low in K1). Elderly with poor diet."),
    ("What is the neonatal vitamin K dose?", "Standard dose per NHM India and WHO: 1 mg phytomenadione (vitamin K1) IM at birth for all neonates ≥32 weeks. Preterm <32 weeks: 0.5 mg IM. Oral K is available (Konakion MM Paediatric 2 mg) but requires 3 doses (at birth, 1 week, 4–6 weeks) — less reliable than single IM dose. IM vitamin K prevents haemorrhagic disease of the newborn (HDN) with near 100% efficacy."),
    ("How is vitamin K given to reverse warfarin?", "Warfarin reversal: Non-bleeding, INR >5: withhold warfarin 1–2 doses, recheck INR. Non-bleeding, INR >8: oral vitamin K 1–5 mg. Bleeding with elevated INR: IV vitamin K 5–10 mg slow infusion (over 20–60 min — anaphylaxis risk with rapid infusion) + urgent 4-factor PCC (prothrombin complex concentrate) for immediate reversal. INR normalises with vitamin K in 4–6 hours (IV) or 12–24 hours (oral). For surgery: aim INR <1.5."),
    ("What is the interaction between vitamin K and warfarin?", "Warfarin works by inhibiting vitamin K epoxide reductase (VKOR), preventing recycling of vitamin K and depleting active vitamin K. Foods high in vitamin K1 (green leafy vegetables: spinach, kale, broccoli, methi/fenugreek — commonly eaten in India) reduce warfarin efficacy. Patients on warfarin should maintain consistent (not zero) daily vitamin K intake rather than avoiding it completely. Sudden dietary changes (more or less green vegetables) destabilise INR."),
],
"rabies-scheduler/doses": [
    ("What is the NCDC India rabies PEP schedule?", "NCDC India recommends the 4-dose Essen IM regimen: Day 0 (2 doses at two sites), Day 7, Day 21. Each dose is 1 vial of tissue culture vaccine (1 mL IM in deltoid for adults, anterolateral thigh for infants). This replaces the older 5-dose schedule. The Zagreb 2-1-1 regimen (Day 0 ×2, Day 7, Day 21) is also endorsed by NCDC and requires only 4 visits and 4 vials."),
    ("Who needs rabies immunoglobulin (RIG)?", "RIG is indicated for all Category III exposures (deep bite penetrating skin, multiple bites, bites on face/head/neck/fingers/genitalia, licks on mucous membranes or broken skin) in unvaccinated or incompletely vaccinated individuals. Equine RIG (ERIG) 40 IU/kg or Human RIG (HRIG) 20 IU/kg — infiltrate maximum possible dose into and around wound, give remainder IM at distant site. Give on Day 0 with first vaccine dose."),
    ("What are the WHO exposure categories?", "Category I: touching/feeding animals, licks on intact skin — no PEP needed, wash hands. Category II: nibbling of uncovered skin, minor scratches without bleeding — wound wash + vaccine only, no RIG. Category III: single or multiple transdermal bites/scratches, contamination of mucous membrane with saliva, licks on broken skin, exposure to bats — wound wash + vaccine + RIG. All Category II and III require immediate wound washing with soap and water for ≥15 minutes."),
    ("What if the rabies vaccine series is interrupted?", "Do not restart the series. Resume from where it was interrupted. The immune response is maintained as long as the series is completed — the timing of interruption does not reset the schedule. Complete all remaining doses as per original schedule dates. If a dose is late, give it as soon as possible and continue on the original schedule."),
    ("Is rabies vaccine safe in pregnancy?", "Yes. Rabies PEP is not contraindicated in pregnancy. The risk of rabies (100% fatal) far outweighs any theoretical vaccine risk. Cell culture rabies vaccines (HDCV, PVRV, PCECV) are safe in pregnancy. Nerve tissue vaccines (Semple — being phased out in India) are avoided. RIG is also safe in pregnancy. Never withhold PEP from a pregnant woman with Category II or III exposure."),
    ("What wounds have highest rabies transmission risk?", "Highest risk: bites on face, head, neck, and hands (rich nerve supply — shorter incubation period), deep penetrating wounds (more virus inoculated), multiple wounds, wounds not washed immediately. Lower risk: scratches, superficial bites on limbs. Incubation period ranges from 5 days to several years (average 1–3 months) — determined by viral load inoculated, wound location, and host immune status. Immediate wound washing reduces transmission risk by >50%."),
],
}

def main():
    repo = Path.cwd()
    modified = []

    for slug, faq_list in FAQS.items():
        # Handle vitamin and rabies subdirectory slugs
        if "/" in slug:
            html_file = repo / f"{slug}.html"
        else:
            html_file = repo / "medical-calculators" / f"{slug}.html"

        if not html_file.exists():
            print(f"  ⚠️  Not found: {html_file}")
            continue

        original = html_file.read_text(encoding="utf-8", errors="ignore")
        content = original

        # Skip if already has substantial FAQ content
        fq_count = len(re.findall(r'class=["\'][^"\']*(?:fi|fq|faq-item|faq-q)["\']', content))
        h3_in_faq = len(re.findall(r'(?:FAQ|Frequently Asked).*?<h3', content, re.DOTALL | re.IGNORECASE))
        schema_q = len(re.findall(r'"@type"\s*:\s*"Question"', content))

        if fq_count >= 4 or h3_in_faq >= 4 or schema_q >= 4:
            print(f"  ⏭️  {slug} — already has FAQ ({fq_count} fi, {h3_in_faq} h3, {schema_q} schema)")
            continue

        # Add CSS if needed
        if 'class="fi"' not in content and '.fi{' not in content and '.fi ' not in content:
            if '</style>' in content:
                content = content.replace('</style>', FAQ_CSS + '\n  </style>', 1)

        # Build FAQ HTML
        faq_html = build_faq_html(faq_list)

        # Add JS toggle if not present
        if 'function tf(' not in content and '</script>' in content:
            # inject before last </script>
            last_script = content.rfind('</script>')
            content = content[:last_script] + FAQ_JS + '\n' + content[last_script:]

        # Inject FAQ before </body>
        if '</body>' in content:
            content = content.replace('</body>', faq_html + '\n</body>', 1)
        else:
            content += faq_html

        if content != original:
            shutil.copy2(html_file, str(html_file) + ".bak")
            html_file.write_text(content, encoding="utf-8")
            modified.append(slug)
            print(f"  ✅ {slug} — {len(faq_list)} FAQs injected")

    print(f"\n{'='*50}")
    print(f"Modified: {len(modified)} files")
    if modified:
        print("Run: git add -A && git commit -m 'fix: FAQ sections added to remaining pages' && git push")

if __name__ == "__main__":
    main()
